# Copyright © 2021 Dell Inc. or its subsidiaries. All Rights Reserved.
# This software is protected, without limitation, by copyright law and international treaties.
# Use of this software and the intellectual property contained therein is expressly limited to the terms and conditions of the
# License Agreement under which it is provided by or on behalf of Dell Inc or its subsidiaries.

# Token created on 30.09.2021
# Token expiry on 01.09.2022 (Exact Expiry Date 01.10.2022)
# SVC_Account : svc_npansible
# Collection version depends on the branches, which need to be changed according to the merged branch
---
collections:
# Geneneric NGCS common collection 
  - name: https://gitlab.dell.com/api/v4/projects/112672/packages/generic/ngcs-common_collection/1.0.3/ngcs-common_collection-1.0.3.tar.gz?private_token=1-5FZzt64CDf-NqgZ-am

# External VMware collections
  - name: https://gitlab.dell.com/api/v4/projects/128160/packages/generic/ngcs-vmware_collection/1.0.3/ngcs-vmware_collection-1.0.3.tar.gz?private_token=1-5FZzt64CDf-NqgZ-am
