# This software is protected, without limitation, by copyright law and 
# international treaties. Use of this software and the intellectual property 
# contained therein is expressly limited to the terms and conditions of the 
# License Agreement under which it is provided by or on behalf of Dell Inc 
# or its subsidiaries.
FROM quay.io/ansible/toolset:3.5.0

ENV container docker
COPY ./post_provisioning/ /services/

# default vault password for storing endpoint secrets
RUN mkdir -p /vault && echo 'changeme' > /vault/.vault_pass
ENV ANSIBLE_VAULT_PASSWORD_FILE=/vault/.vault_pass

# Add colon-separated lib directories for Ansible Modules
ENV ANSIBLE_LIBRARY /services/plugins/modules
ENV ANSIBLE_MODULE_UTILS /services/plugins/module_utils
ENV ANSIBLE_COLLECTIONS_PATHS /services/collections
ENV ANSIBLE_COLLECTIONS_PATH /services/collections

# Install python dependencies
RUN python3 -m pip install -r /services/requirements.txt
RUN python3 -m pip install requests
WORKDIR /services

# Keep the container up
ENTRYPOINT tail -f /dev/null
