---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c ../common/.yamllint ./molecule/test_fail_to_ipam_remove_when_invalid_vm_fqdn/*.yml
  ansible-lint -c ../common/.ansible-lint -x behaviour,metadata ./tasks/*.yml
driver:
  name: delegated
  managed: false
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
scenario:
  test_sequence:
    - dependency
    - lint
    - syntax
    - prepare
    - converge
    - verify
    - cleanup
provisioner:
  name: ansible
verifier:
  name: ansible
